/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic.pkgpackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author PeiPei
 */
public class Drawing extends javax.swing.JFrame {

    /**
     * Creates new form Drawing
     */
    MethodClass MC;
    public static JTree tree;
    public Drawing() 
    {
        MC=new MethodClass();
        initComponents();
        
        pnldraw.setLayout(new BorderLayout());  //to draw on the panel
        pnldraw.add(MC, BorderLayout.CENTER);   //to add the JComponet
        
        
        //---------------------------------------------------------------------
        DefaultMutableTreeNode root=new DefaultMutableTreeNode(UserLogin.UN + "'s Pictures"); //create root for Jtree
        String []names=(new File("C:\\"+ UserLogin.UN).list());
        for (String name : names)
        {
            DefaultMutableTreeNode node=new DefaultMutableTreeNode(name);
            root.add(node);
        }
        
        tree=new JTree(root);               //placing Jtree on the panel
        pnlsave.setLayout(new BorderLayout());
        pnlsave.add(tree, BorderLayout.CENTER);
        //--------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnPen = new javax.swing.JButton();
        btnLine = new javax.swing.JButton();
        btneraser = new javax.swing.JButton();
        btncircle = new javax.swing.JButton();
        btnrectangle = new javax.swing.JButton();
        btntri = new javax.swing.JButton();
        btnroundrec = new javax.swing.JButton();
        btnpenta = new javax.swing.JButton();
        btnrighttri = new javax.swing.JButton();
        btnstar = new javax.swing.JButton();
        btntext = new javax.swing.JButton();
        btnfill = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        boxpensize = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnwhite = new javax.swing.JButton();
        btngray = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnblue = new javax.swing.JButton();
        btnpurple = new javax.swing.JButton();
        btnlightblue = new javax.swing.JButton();
        btnpink = new javax.swing.JButton();
        btnbrown = new javax.swing.JButton();
        btnred = new javax.swing.JButton();
        btngreen = new javax.swing.JButton();
        btnlightgreen = new javax.swing.JButton();
        btnyellow = new javax.swing.JButton();
        btnorange = new javax.swing.JButton();
        btncolor = new javax.swing.JButton();
        pnldraw = new javax.swing.JPanel();
        pnlsave = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnremove = new javax.swing.JButton();
        btnresave = new javax.swing.JButton();
        btnopenpic = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnclear = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Shapes and Tools"));

        btnPen.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\pen.PNG")); // NOI18N
        btnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenActionPerformed(evt);
            }
        });

        btnLine.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\line.PNG")); // NOI18N
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });

        btneraser.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\eraser.JPG")); // NOI18N
        btneraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneraserActionPerformed(evt);
            }
        });

        btncircle.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\circle.PNG")); // NOI18N
        btncircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncircleActionPerformed(evt);
            }
        });

        btnrectangle.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\rectangle.PNG")); // NOI18N
        btnrectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrectangleActionPerformed(evt);
            }
        });

        btntri.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\Triangle.png")); // NOI18N
        btntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntriActionPerformed(evt);
            }
        });

        btnroundrec.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\round rec.png")); // NOI18N
        btnroundrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundrecActionPerformed(evt);
            }
        });

        btnpenta.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\penta.png")); // NOI18N
        btnpenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpentaActionPerformed(evt);
            }
        });

        btnrighttri.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\righttri.png")); // NOI18N
        btnrighttri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrighttriActionPerformed(evt);
            }
        });

        btnstar.setIcon(new javax.swing.ImageIcon("C:\\SU HTET THINZAR_00172597\\Graphic Package\\Star.png")); // NOI18N
        btnstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstarActionPerformed(evt);
            }
        });

        btntext.setText("A");
        btntext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntextActionPerformed(evt);
            }
        });

        btnfill.setBackground(new java.awt.Color(204, 204, 204));
        btnfill.setText("Fill");
        btnfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfillActionPerformed(evt);
            }
        });

        jLabel1.setText("Brush size:");

        boxpensize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        boxpensize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxpensizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btntext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnstar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpenta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnfill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnPen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnroundrec, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnrectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLine, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btncircle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btneraser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnrighttri, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxpensize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneraser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLine, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncircle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnroundrec, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrighttri, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntext, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnfill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxpensize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnwhite.setBackground(new java.awt.Color(255, 255, 255));
        btnwhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwhiteActionPerformed(evt);
            }
        });

        btngray.setBackground(new java.awt.Color(153, 153, 153));
        btngray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrayActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnblue.setBackground(new java.awt.Color(0, 51, 204));
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });

        btnpurple.setBackground(new java.awt.Color(153, 0, 255));
        btnpurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpurpleActionPerformed(evt);
            }
        });

        btnlightblue.setBackground(new java.awt.Color(0, 153, 255));
        btnlightblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlightblueActionPerformed(evt);
            }
        });

        btnpink.setBackground(new java.awt.Color(255, 51, 204));
        btnpink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinkActionPerformed(evt);
            }
        });

        btnbrown.setBackground(new java.awt.Color(153, 51, 0));
        btnbrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrownActionPerformed(evt);
            }
        });

        btnred.setBackground(java.awt.Color.red);
        btnred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnredActionPerformed(evt);
            }
        });

        btngreen.setBackground(new java.awt.Color(0, 153, 51));
        btngreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngreenActionPerformed(evt);
            }
        });

        btnlightgreen.setBackground(new java.awt.Color(51, 255, 0));
        btnlightgreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlightgreenActionPerformed(evt);
            }
        });

        btnyellow.setBackground(new java.awt.Color(255, 255, 51));
        btnyellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyellowActionPerformed(evt);
            }
        });

        btnorange.setBackground(new java.awt.Color(255, 153, 51));
        btnorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorangeActionPerformed(evt);
            }
        });

        btncolor.setText("Other Color");
        btncolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btngray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnblue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlightblue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbrown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnyellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnwhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpurple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpink, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlightgreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnorange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(btncolor)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwhite, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btngray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnblue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpurple, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnlightblue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpink, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbrown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnred, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnlightgreen, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btngreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnyellow, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnorange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncolor))
        );

        pnldraw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnldraw.setLayout(new java.awt.BorderLayout());

        pnlsave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlsave.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pic Library"));

        btnremove.setText("remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        btnresave.setText("save");
        btnresave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresaveActionPerformed(evt);
            }
        });

        btnopenpic.setText("open");
        btnopenpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenpicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnremove, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addComponent(btnresave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnopenpic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnremove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnresave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnopenpic))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        btnclear.setText("clear all");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnlogout.setText("log out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnldraw, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnldraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenActionPerformed
        // TODO add your handling code here:
        MC.setShape("Pen");
    }//GEN-LAST:event_btnPenActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
        Color blue=new Color(0, 51, 204);
        MC.setCurrentColor(blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnblueActionPerformed

    private void btngreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngreenActionPerformed
        Color green=new Color(0, 153, 51);
        MC.setCurrentColor(green);
        // TODO add your handling code here:
    }//GEN-LAST:event_btngreenActionPerformed

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        MC.setShape("Line");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLineActionPerformed

    private void btnredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnredActionPerformed
       MC.setCurrentColor(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnredActionPerformed

    private void btnwhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwhiteActionPerformed
        MC.setCurrentColor(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnwhiteActionPerformed

    private void btngrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrayActionPerformed
        Color gray=new Color(153, 153, 153);
        MC.setCurrentColor(gray);
        // TODO add your handling code here:
    }//GEN-LAST:event_btngrayActionPerformed

    private void btnpinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinkActionPerformed
       Color pink=new Color(255, 51, 204);
        MC.setCurrentColor(pink);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpinkActionPerformed

    private void btnbrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrownActionPerformed
        Color bro=new Color(153, 51, 0);
        MC.setCurrentColor(bro);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbrownActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Color C=new Color(255, 204, 204);
        MC.setCurrentColor(C);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnyellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyellowActionPerformed
        Color yellow=new Color(255, 255, 51);
        MC.setCurrentColor(yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnyellowActionPerformed

    private void btnorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorangeActionPerformed
        Color orange=new Color(255, 153, 51);
        MC.setCurrentColor(orange);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnorangeActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        MC.clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncircleActionPerformed
        MC.setShape("Circle");
        // TODO add your handling code here:
    }//GEN-LAST:event_btncircleActionPerformed

    private void btnpurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpurpleActionPerformed
        Color pur=new Color(153, 0, 255);
        MC.setCurrentColor(pur);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpurpleActionPerformed

    private void btnlightblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlightblueActionPerformed
        Color lightb=new Color(0, 153, 255);
        MC.setCurrentColor(lightb);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlightblueActionPerformed

    private void btnlightgreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlightgreenActionPerformed
        Color lightg=new Color(51, 255, 0);
        MC.setCurrentColor(lightg);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlightgreenActionPerformed

    private void btnrectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrectangleActionPerformed
        MC.setShape("Rectangle");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrectangleActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       MC.setCurrentColor(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfillActionPerformed
        boolean f=btnfill.isSelected() ? true: false;   //condition checking
        MC.setshapefill(f);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfillActionPerformed

    private void btntextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntextActionPerformed
        MC.setShape("Text");
        // TODO add your handling code here:
    }//GEN-LAST:event_btntextActionPerformed

    private void boxpensizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxpensizeActionPerformed
        int s=boxpensize.getSelectedIndex();
        MC.setSize(s+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_boxpensizeActionPerformed

    private void btntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntriActionPerformed
        MC.setShape("Triangle");
        // TODO add your handling code here:
    }//GEN-LAST:event_btntriActionPerformed

    private void btneraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneraserActionPerformed
        MC.setShape("Eraser");
        // TODO add your handling code here:
    }//GEN-LAST:event_btneraserActionPerformed

    private void btnroundrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundrecActionPerformed
        MC.setShape("RoundRec");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroundrecActionPerformed

    private void btncolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolorActionPerformed
        Color col=JColorChooser.showDialog(this, "Choose Color", Color.yellow);
        MC.setCurrentColor(col);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncolorActionPerformed

    private void btnpentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpentaActionPerformed
        MC.setShape("Penta");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MC.save();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MC.clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnrighttriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrighttriActionPerformed
        MC.setShape("RightTri");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrighttriActionPerformed

    private void btnstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstarActionPerformed
        MC.setShape("Star");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstarActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        DefaultTreeModel model= (DefaultTreeModel) tree.getModel();
        TreePath[] paths=tree.getSelectionPaths();
        
        for (TreePath path : paths) 
        {
            DefaultMutableTreeNode node=(DefaultMutableTreeNode) path.getLastPathComponent();
            File file=new File("C:\\"+ UserLogin.UN+"\\"+node.toString());
            file.delete();
        }
        JOptionPane.showMessageDialog(null, "Pic has been removed");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnopenpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenpicActionPerformed
        MC.openpic();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnopenpicActionPerformed

    private void btnresaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresaveActionPerformed
        MC.save();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresaveActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        UserLogin UL=new UserLogin();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        UserLogin UL=new UserLogin();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Drawing().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxpensize;
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnPen;
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btnbrown;
    private javax.swing.JButton btncircle;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncolor;
    private javax.swing.JButton btneraser;
    private javax.swing.JCheckBox btnfill;
    private javax.swing.JButton btngray;
    private javax.swing.JButton btngreen;
    private javax.swing.JButton btnlightblue;
    private javax.swing.JButton btnlightgreen;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnopenpic;
    private javax.swing.JButton btnorange;
    private javax.swing.JButton btnpenta;
    private javax.swing.JButton btnpink;
    private javax.swing.JButton btnpurple;
    private javax.swing.JButton btnrectangle;
    private javax.swing.JButton btnred;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnresave;
    private javax.swing.JButton btnrighttri;
    private javax.swing.JButton btnroundrec;
    private javax.swing.JButton btnstar;
    private javax.swing.JButton btntext;
    private javax.swing.JButton btntri;
    private javax.swing.JButton btnwhite;
    private javax.swing.JButton btnyellow;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnldraw;
    private javax.swing.JPanel pnlsave;
    // End of variables declaration//GEN-END:variables
}
